    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        provenance: false # Add this line
        tags: ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest

