- name: Build and push Docker image
  uses: docker/build-push-action@v5
  with:
    context: .
    push: true
    provenance: false
    tags: |
      akusoife1/my-python-app:latest
      akusoife1/my-python-app:${{ github.sha }}

